AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: TypeScript Lambda Function with API Gateway

Parameters:
  AnthropicApiKey:
    Type: String
    Description: Anthropic API Key for Claude
    NoEcho: true

Globals:
  Function:
    Timeout: 180
    MemorySize: 256
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: production
        ANTHROPIC_API_KEY: !Ref AnthropicApiKey

Resources:
  ThinkTwiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /consult
            Method: get
            RestApiId: !Ref ThinkTwiceApi
        PostEvent:
          Type: Api
          Properties:
            Path: /consult
            Method: post
            RestApiId: !Ref ThinkTwiceApi
        OptionsEvent:
          Type: Api
          Properties:
            Path: /consult
            Method: options
            RestApiId: !Ref ThinkTwiceApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/index.ts

  ThinkTwiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET, POST, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

Outputs:
  ThinkTwiceApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ThinkTwiceApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/consult"
  ThinkTwiceFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ThinkTwiceFunction.Arn
  ThinkTwiceFunctionIamRole:
    Description: "IAM Role for Lambda Function"
    Value: !GetAtt ThinkTwiceFunctionRole.Arn
