AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: TypeScript Lambda Function with API Gateway

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  ThinkTwiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /consult
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /consult
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/index.ts

Outputs:
  ThinkTwiceApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ThinkTwiceFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ThinkTwiceFunction.Arn
  ThinkTwiceFunctionIamRole:
    Description: "IAM Role for Lambda Function"
    Value: !GetAtt ThinkTwiceFunctionRole.Arn
